"use client";

import { useState } from "react";
import Link from "next/link";
import Navbar from "../components/Navbar";

/* ── Types ───────────────────────────────────────────── */
interface Col {
  id: string;
  name: string;
  type: string;
  pk: boolean;
  nullable: boolean;
}

/* ── SQL Data Types ──────────────────────────────────── */
const SQL_TYPES = [
  "INT","BIGINT","SMALLINT","TINYINT","BIT",
  "DECIMAL(18,2)","NUMERIC(18,2)","FLOAT","REAL","MONEY",
  "CHAR(10)","VARCHAR(50)","VARCHAR(100)","VARCHAR(200)","VARCHAR(MAX)",
  "NVARCHAR(50)","NVARCHAR(100)","NVARCHAR(200)","NVARCHAR(MAX)",
  "TEXT","NTEXT","DATE","DATETIME","DATETIME2","TIME","UNIQUEIDENTIFIER",
];

let uid = 1;
const mkCol = (): Col => ({
  id: String(uid++),
  name: "",
  type: "NVARCHAR(100)",
  pk: false,
  nullable: true,
});

/* ── SQL builders ────────────────────────────────────── */
function buildCreate(tableName: string, cols: Col[]): string {
  const L: string[] = [];
  L.push(`CREATE TABLE [dbo].[tbl_${tableName}]`);
  L.push("(");
  cols.forEach((c) => {
    const nn = c.pk ? "NOT NULL" : c.nullable ? "NULL" : "NOT NULL";
    L.push(`    [${c.name || "Column"}]  ${c.type}  ${nn},`);
  });
  const pks = cols.filter((c) => c.pk).map((c) => `[${c.name}]`);
  if (pks.length) {
    L[L.length - 1] = L[L.length - 1].replace(/,$/, "");
    L.push(`    CONSTRAINT [PK_tbl_${tableName}] PRIMARY KEY (${pks.join(", ")})`);
  } else {
    L[L.length - 1] = L[L.length - 1].replace(/,$/, "");
  }
  L.push(")");
  L.push("GO");
  return L.join("\n");
}

function buildProc(dbName: string, tableName: string, cols: Col[]): string {
  const tbl = `tbl_${tableName}`;
  const proc = `sp_${tableName}`;
  const pk = cols.find((c) => c.pk);
  const d = new Date();
  const dt = `${String(d.getDate()).padStart(2,"0")}-${String(d.getMonth()+1).padStart(2,"0")}-${d.getFullYear()}`;
  const L: string[] = [];

  L.push(`USE [${dbName}]`);
  L.push("GO");
  L.push("SET ANSI_NULLS ON");
  L.push("GO");
  L.push("SET QUOTED_IDENTIFIER ON");
  L.push("GO");
  L.push("-- =============================================");
  L.push("-- Author      : Auto Generated by iNeedTools");
  L.push(`-- Create Date : ${dt}`);
  L.push("-- Description : Dynamic CRUD Procedure");
  L.push("-- =============================================");
  L.push(`ALTER PROCEDURE [dbo].[${proc}]`);
  L.push("    @Type      VARCHAR(10)   = NULL,");
  L.push("    @JsonData  NVARCHAR(MAX) = NULL" + (pk ? "," : ""));
  if (pk) L.push(`    @${pk.name}  ${pk.type}  = NULL`);
  L.push("AS");
  L.push("BEGIN");
  L.push("    SET NOCOUNT ON;");
  L.push("");
  L.push("    -- ── SELECT ALL ──────────────────────────");
  L.push("    IF @Type = 'ALL'");
  L.push(`        SELECT * FROM [dbo].[${tbl}] FOR JSON PATH`);
  L.push("");
  L.push("    -- ── SELECT ACTIVE ───────────────────────");
  L.push("    ELSE IF @Type = 'ACT'");
  L.push(`        SELECT * FROM [dbo].[${tbl}] WHERE Status = 0 FOR JSON PATH`);
  L.push("");
  if (pk) {
    L.push("    -- ── SELECT BY ID ────────────────────────");
    L.push("    ELSE IF @Type = 'SEL'");
    L.push(`        SELECT * FROM [dbo].[${tbl}]`);
    L.push(`        WHERE [${pk.name}] = @${pk.name}`);
    L.push("        FOR JSON PATH, WITHOUT_ARRAY_WRAPPER");
    L.push("");
  }
  L.push("    -- ── INSERT / UPDATE (MERGE) ─────────────");
  L.push("    ELSE IF @Type = 'INS'");
  L.push(`        MERGE INTO [dbo].[${tbl}] AS t`);
  L.push("        USING (");
  L.push("            SELECT * FROM OPENJSON(@JsonData)");
  L.push("            WITH (");
  cols.forEach((c, i) => {
    const comma = i < cols.length - 1 ? "," : "";
    L.push(`                [${c.name || "col"}]  ${c.type}${comma}`);
  });
  L.push("            )");
  L.push("        ) AS s");
  if (pk) L.push(`        ON t.[${pk.name}] = s.[${pk.name}]`);
  L.push("        WHEN MATCHED THEN UPDATE SET");
  const upd = cols.filter((c) => !c.pk);
  upd.forEach((c, i) => {
    L.push(`            t.[${c.name}] = s.[${c.name}]${i < upd.length - 1 ? "," : ""}`);
  });
  L.push("        WHEN NOT MATCHED BY TARGET THEN INSERT (");
  L.push("            " + cols.map((c) => `[${c.name}]`).join(", "));
  L.push("        ) VALUES (");
  const vals = cols.map((c) =>
    c.pk && c.type.toUpperCase().includes("UNIQUEIDENTIFIER") ? "NEWID()" : `s.[${c.name}]`
  );
  L.push("            " + vals.join(", "));
  L.push("        );");
  if (pk) {
    L.push("");
    L.push("    -- ── DELETE ──────────────────────────────");
    L.push("    ELSE IF @Type = 'DEL'");
    L.push(`        DELETE FROM [dbo].[${tbl}] WHERE [${pk.name}] = @${pk.name}`);
  }
  L.push("");
  L.push("END");
  L.push("GO");
  return L.join("\n");
}

/* ══════════════════════════════════════════════════════
   Component
═══════════════════════════════════════════════════════ */
export default function SqlGeneratorPage() {
  const [dbName, setDbName]     = useState("YourDatabase");
  const [tableName, setTableName] = useState("YourTable");
  const [cols, setCols]         = useState<Col[]>([mkCol()]);
  const [createSql, setCreateSql] = useState("");
  const [procSql, setProcSql]   = useState("");
  const [activeTab, setActiveTab] = useState(0);
  const [copied, setCopied]     = useState("");
  const [generated, setGenerated] = useState(false);

  const updateCol = (id: string, patch: Partial<Col>) =>
    setCols((prev) => prev.map((c) => (c.id === id ? { ...c, ...patch } : c)));

  const setPK = (id: string, val: boolean) =>
    setCols((prev) =>
      prev.map((c) => ({
        ...c,
        pk: c.id === id ? val : false,
        nullable: c.id === id && val ? false : c.nullable,
      }))
    );

  const generate = () => {
    setCreateSql(buildCreate(tableName, cols));
    setProcSql(buildProc(dbName, tableName, cols));
    setActiveTab(0);
    setGenerated(true);
  };

  const copy = async (text: string, key: string) => {
    try { await navigator.clipboard.writeText(text); } catch { /**/ }
    setCopied(key);
    setTimeout(() => setCopied(""), 2200);
  };

  const activeSql = activeTab === 0 ? createSql : procSql;

  /* ── styles (inline to stay self-contained) ── */
  const card: React.CSSProperties = {
    background: "#ffffff",
    border: "1px solid rgba(0,0,0,0.08)",
    borderRadius: 16,
    overflow: "hidden",
    boxShadow: "0 2px 16px rgba(37,99,235,0.07)",
    marginBottom: 20,
  };
  const cardHead: React.CSSProperties = {
    background: "#f8f9ff",
    borderBottom: "1px solid rgba(0,0,0,0.07)",
    padding: "14px 22px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  };
  const th: React.CSSProperties = {
    padding: "10px 14px",
    textAlign: "left",
    fontSize: 11,
    fontWeight: 700,
    color: "rgba(15,10,30,0.4)",
    letterSpacing: "0.07em",
    textTransform: "uppercase",
    background: "#fafbff",
    borderBottom: "1px solid rgba(0,0,0,0.07)",
  };
  const td: React.CSSProperties = { padding: "9px 14px", verticalAlign: "middle" };

  return (
    <div style={{ background: "#ffffff" }} className="min-h-screen flex flex-col">
      <Navbar />

      {/* ── Hero ─────────────────────────────────────── */}
      <section style={{ background:"linear-gradient(135deg,#f0f4ff 0%,#f5f3ff 50%,#fff 100%)", padding:"56px 24px 48px" }}>
        <div style={{ maxWidth:960, margin:"0 auto" }}>
          <p className="section-label mb-2">Database Tool</p>
          <div className="section-line" style={{ margin:"0 0 18px" }} />
          <h1 className="font-black tracking-tight mb-4"
            style={{ fontSize:"clamp(32px,5vw,56px)", color:"#0f0a1e", lineHeight:1.1 }}>
            SQL{" "}<span className="text-gradient-purple">Generator</span>
          </h1>
          <p style={{ color:"rgba(15,10,30,0.52)", fontSize:16, maxWidth:520, lineHeight:1.75, marginBottom:20 }}>
            Define your columns, hit <strong>Generate SQL</strong> — get a ready-to-use{" "}
            <code style={{ background:"rgba(37,99,235,0.08)", padding:"2px 6px", borderRadius:4, fontSize:13 }}>CREATE TABLE</code>{" "}
            and a full dynamic CRUD stored procedure in seconds.
          </p>
          <div style={{ display:"flex", flexWrap:"wrap", gap:8 }}>
            {["CREATE TABLE","ALTER PROCEDURE","MERGE / CRUD","JSON Output","FOR JSON PATH"].map(t => (
              <span key={t} className="badge badge-blue" style={{ fontSize:10 }}>{t}</span>
            ))}
          </div>
        </div>
      </section>

      {/* ── Tool ─────────────────────────────────────── */}
      <div style={{ maxWidth:960, margin:"36px auto 60px", padding:"0 24px", width:"100%" }}>

        {/* DB + Table name */}
        <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:16, marginBottom:24 }}>
          <div>
            <label style={{ fontSize:11,fontWeight:700,color:"rgba(15,10,30,0.45)",display:"block",marginBottom:6,letterSpacing:"0.07em",textTransform:"uppercase" }}>
              Database Name
            </label>
            <input className="field" value={dbName} onChange={e => setDbName(e.target.value)} placeholder="e.g. MyDatabase" />
          </div>
          <div>
            <label style={{ fontSize:11,fontWeight:700,color:"rgba(15,10,30,0.45)",display:"block",marginBottom:6,letterSpacing:"0.07em",textTransform:"uppercase" }}>
              Table Name
            </label>
            <input className="field" value={tableName} onChange={e => setTableName(e.target.value)} placeholder="e.g. Employees" />
          </div>
        </div>

        {/* Columns card */}
        <div style={card}>
          <div style={cardHead}>
            <div>
              <p style={{ fontWeight:700, fontSize:14, color:"#0f0a1e" }}>Column Definitions</p>
              <p style={{ fontSize:12, color:"rgba(15,10,30,0.42)", marginTop:2 }}>
                {cols.length} column{cols.length !== 1 ? "s" : ""} defined
              </p>
            </div>
            <button
              onClick={() => setCols(p => [...p, mkCol()])}
              className="btn btn-primary btn-sm"
              style={{ gap:6 }}
            >
              + Add Column
            </button>
          </div>

          <div style={{ overflowX:"auto" }}>
            <table style={{ width:"100%", borderCollapse:"collapse" }}>
              <thead>
                <tr>
                  <th style={th}>Column Name</th>
                  <th style={th}>Data Type</th>
                  <th style={{ ...th, textAlign:"center" }}>Primary Key</th>
                  <th style={{ ...th, textAlign:"center" }}>Nullable</th>
                  <th style={th}></th>
                </tr>
              </thead>
              <tbody>
                {cols.map((col, idx) => (
                  <tr key={col.id} style={{ borderBottom: idx < cols.length - 1 ? "1px solid rgba(0,0,0,0.05)" : "none" }}>
                    <td style={td}>
                      <input
                        className="field"
                        style={{ fontSize:13, padding:"8px 11px" }}
                        value={col.name}
                        onChange={e => updateCol(col.id, { name: e.target.value })}
                        placeholder={`Column${idx + 1}`}
                      />
                    </td>
                    <td style={td}>
                      <select
                        className="select-field"
                        style={{ width:"100%", fontSize:13, padding:"8px 11px" }}
                        value={col.type}
                        onChange={e => updateCol(col.id, { type: e.target.value })}
                      >
                        {SQL_TYPES.map(t => <option key={t} value={t}>{t}</option>)}
                      </select>
                    </td>
                    <td style={{ ...td, textAlign:"center" }}>
                      <input
                        type="checkbox"
                        checked={col.pk}
                        onChange={e => setPK(col.id, e.target.checked)}
                        style={{ width:16, height:16, accentColor:"#7c3aed", cursor:"pointer" }}
                      />
                    </td>
                    <td style={{ ...td, textAlign:"center" }}>
                      <input
                        type="checkbox"
                        checked={col.nullable}
                        disabled={col.pk}
                        onChange={e => updateCol(col.id, { nullable: e.target.checked })}
                        style={{ width:16, height:16, accentColor:"#7c3aed", cursor:col.pk ? "not-allowed" : "pointer", opacity:col.pk ? 0.35 : 1 }}
                      />
                    </td>
                    <td style={td}>
                      <button
                        onClick={() => setCols(p => p.filter(c => c.id !== col.id))}
                        style={{ background:"rgba(225,29,72,0.07)",border:"1px solid rgba(225,29,72,0.18)",borderRadius:8,padding:"6px 10px",color:"#e11d48",cursor:"pointer",fontSize:14,lineHeight:1,display:"flex",alignItems:"center" }}
                        title="Remove column"
                      >
                        ✕
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Generate button */}
        <button
          onClick={generate}
          className="btn btn-primary"
          style={{ fontSize:15, padding:"14px 34px", marginBottom:32 }}
        >
          ⚡ Generate SQL
        </button>

        {/* Output */}
        {generated && (
          <div>
            {/* Tabs */}
            <div style={{ display:"flex", gap:4, borderBottom:"1px solid rgba(0,0,0,0.1)", marginBottom:0 }}>
              {["CREATE TABLE","Stored Procedure"].map((tab, i) => (
                <button
                  key={tab}
                  onClick={() => setActiveTab(i)}
                  style={{
                    padding:"10px 22px",
                    borderRadius:"10px 10px 0 0",
                    border: activeTab === i ? "1px solid rgba(0,0,0,0.1)" : "1px solid transparent",
                    borderBottom: activeTab === i ? "1px solid #fff" : "1px solid transparent",
                    background: activeTab === i ? "#fff" : "transparent",
                    color: activeTab === i ? "#7c3aed" : "rgba(15,10,30,0.45)",
                    fontSize:13, fontWeight:700, cursor:"pointer",
                    position:"relative", top:1, transition:"all 0.2s",
                  }}
                >
                  {tab}
                </button>
              ))}
            </div>

            {/* Code block */}
            <div style={{
              fontFamily:"var(--font-mono,'Courier New',monospace)", fontSize:12.5,
              background:"#0f172a", color:"#e2e8f0",
              borderRadius:"0 14px 14px 14px", padding:"24px 28px",
              overflowX:"auto", lineHeight:1.85, whiteSpace:"pre",
              boxShadow:"0 4px 24px rgba(0,0,0,0.14)",
            }}>
              {activeSql}
            </div>

            {/* Copy row */}
            <div style={{ display:"flex", justifyContent:"flex-end", marginTop:12, gap:10 }}>
              <button
                onClick={() => copy(activeSql, "sql")}
                className="btn btn-primary btn-sm"
                style={{ minWidth:120 }}
              >
                {copied === "sql" ? "✓ Copied!" : "Copy SQL"}
              </button>
            </div>
          </div>
        )}

        {/* Back link */}
        <div style={{ marginTop:48 }}>
          <Link href="/" style={{ display:"inline-flex",alignItems:"center",gap:6,fontSize:13,fontWeight:600,color:"#7c3aed",textDecoration:"none" }}>
            ← Back to iNeedTools
          </Link>
        </div>
      </div>

      {/* Footer */}
      <footer className="mt-auto py-8 text-center"
        style={{ borderTop:"1px solid rgba(124,58,237,0.1)", fontSize:13, color:"rgba(15,10,30,0.35)" }}>
        <p>© 2026 iNeedTools &nbsp;·&nbsp; SQL Generator</p>
      </footer>
    </div>
  );
}
